"""add suitable_for_children to pois and tourism_validation_log

Revision ID: 10e0bb02e91f
Revises: 69c5bf057c76
Create Date: 2026-03-31 22:29:55.197325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10e0bb02e91f'
down_revision: Union[str, None] = '69c5bf057c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poi_tourism_validation_logs', sa.Column('llm1_suitable_for_children', sa.Boolean(), nullable=True))
    op.add_column('poi_tourism_validation_logs', sa.Column('llm2_suitable_for_children', sa.Boolean(), nullable=True))
    op.add_column('poi_tourism_validation_logs', sa.Column('final_suitable_for_children', sa.Boolean(), nullable=True))
    op.add_column('pois', sa.Column('suitable_for_children', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pois', 'suitable_for_children')
    op.drop_column('poi_tourism_validation_logs', 'final_suitable_for_children')
    op.drop_column('poi_tourism_validation_logs', 'llm2_suitable_for_children')
    op.drop_column('poi_tourism_validation_logs', 'llm1_suitable_for_children')
    # ### end Alembic commands ###
