"""add_tourism_validation

Revision ID: 127ea699f0bf
Revises: cff274140002
Create Date: 2026-03-27 19:34:51.882848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127ea699f0bf'
down_revision: Union[str, None] = 'cff274140002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi_tourism_validation_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('poi_id', sa.Uuid(), nullable=False),
    sa.Column('poi_name', sa.String(length=255), nullable=False),
    sa.Column('poi_types', sa.String(length=500), nullable=True),
    sa.Column('poi_rating', sa.Float(), nullable=True),
    sa.Column('poi_ratings_total', sa.Integer(), nullable=True),
    sa.Column('city_name', sa.String(length=100), nullable=True),
    sa.Column('pipeline_run_id', sa.String(length=100), nullable=True),
    sa.Column('llm1_is_touristic', sa.Boolean(), nullable=True),
    sa.Column('llm1_visit_type', sa.String(length=10), nullable=True),
    sa.Column('llm1_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('llm1_confidence', sa.String(length=10), nullable=True),
    sa.Column('llm1_reasoning', sa.Text(), nullable=True),
    sa.Column('llm2_is_touristic', sa.Boolean(), nullable=True),
    sa.Column('llm2_visit_type', sa.String(length=10), nullable=True),
    sa.Column('llm2_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('llm2_reasoning', sa.Text(), nullable=True),
    sa.Column('llm2_was_needed', sa.Boolean(), nullable=False),
    sa.Column('final_is_touristic', sa.Boolean(), nullable=True),
    sa.Column('final_visit_type', sa.String(length=10), nullable=True),
    sa.Column('final_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('decision_source', sa.String(length=20), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pois', sa.Column('is_touristic', sa.Boolean(), nullable=True))
    op.add_column('pois', sa.Column('tourism_visit_type', sa.String(length=10), nullable=True))
    op.add_column('pois', sa.Column('tourism_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('pois', sa.Column('tourism_validated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pois', 'tourism_validated_at')
    op.drop_column('pois', 'tourism_duration_minutes')
    op.drop_column('pois', 'tourism_visit_type')
    op.drop_column('pois', 'is_touristic')
    op.drop_table('poi_tourism_validation_logs')
    # ### end Alembic commands ###
