"""soft delete city_experiences

Revision ID: 1a4dac0e3ebf
Revises: d2b427d115cc
Create Date: 2026-03-23 21:19:16.452952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a4dac0e3ebf'
down_revision: Union[str, None] = 'd2b427d115cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city_experiences', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('city_experiences', 'is_deleted')
    # ### end Alembic commands ###
