"""add explicit feature columns to pois

Revision ID: 2c99a47cab23
Revises: 2cb32d27a471
Create Date: 2026-03-24 21:12:03.578306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c99a47cab23'
down_revision: Union[str, None] = '2cb32d27a471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pois', sa.Column('nature', sa.Float(), nullable=True))
    op.add_column('pois', sa.Column('culture', sa.Float(), nullable=True))
    op.add_column('pois', sa.Column('food', sa.Float(), nullable=True))
    op.add_column('pois', sa.Column('adventure', sa.Float(), nullable=True))
    op.add_column('pois', sa.Column('nightlife', sa.Float(), nullable=True))
    op.add_column('pois', sa.Column('relax', sa.Float(), nullable=True))
    op.add_column('pois', sa.Column('family_friendly', sa.Float(), nullable=True))
    # ### end Alembic commands ###
    op.execute("""
        UPDATE pois SET
            nature          = feature_vector[1],
            culture         = feature_vector[2],
            food            = feature_vector[3],
            adventure       = feature_vector[4],
            nightlife       = feature_vector[5],
            relax           = feature_vector[6],
            family_friendly = feature_vector[7]
        WHERE feature_vector IS NOT NULL
          AND array_length(feature_vector, 1) = 7
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pois', 'family_friendly')
    op.drop_column('pois', 'relax')
    op.drop_column('pois', 'nightlife')
    op.drop_column('pois', 'adventure')
    op.drop_column('pois', 'food')
    op.drop_column('pois', 'culture')
    op.drop_column('pois', 'nature')
    # ### end Alembic commands ###
