"""replace places with cities and pois

Revision ID: 2cb32d27a471
Revises: 0cef7cc4ae3d
Create Date: 2026-03-24 20:18:22.425490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cb32d27a471'
down_revision: Union[str, None] = '0cef7cc4ae3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pois',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('google_place_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('user_ratings_total', sa.Integer(), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('photo_reference', sa.Text(), nullable=True),
    sa.Column('travel_category', sa.String(length=50), nullable=True),
    sa.Column('feature_vector', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('classified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_place_id')
    )
    op.drop_constraint(op.f('itinerary_items_place_id_fkey'), 'itinerary_items', type_='foreignkey')
    op.drop_table('place_features')
    op.drop_table('places')
    op.create_foreign_key(None, 'itinerary_items', 'pois', ['place_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'itinerary_items', type_='foreignkey')
    op.create_foreign_key(op.f('itinerary_items_place_id_fkey'), 'itinerary_items', 'places', ['place_id'], ['id'])
    op.create_table('places',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('visit_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('opening_hours', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('places_pkey'))
    )
    op.create_table('place_features',
    sa.Column('place_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('culture', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('food', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('adventure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('nightlife', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('relax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('family_friendly', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('place_features_place_id_fkey')),
    sa.PrimaryKeyConstraint('place_id', name=op.f('place_features_pkey'))
    )
    op.drop_table('pois')
    op.drop_table('cities')
    # ### end Alembic commands ###
