"""replace photo_reference with photo_url r2

Revision ID: 34481a25f88b
Revises: ed339d1c5e81
Create Date: 2026-03-23 15:08:58.344845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34481a25f88b'
down_revision: Union[str, None] = 'ed339d1c5e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city_experiences', sa.Column('photo_url', sa.Text(), nullable=True))
    op.drop_column('city_experiences', 'photo_reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city_experiences', sa.Column('photo_reference', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('city_experiences', 'photo_url')
    # ### end Alembic commands ###
