"""add_visited_at_to_itinerary_items

Revision ID: 386a97b0d8fd
Revises: 4a3b9f1d2c7e
Create Date: 2026-03-25 16:32:03.957545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386a97b0d8fd'
down_revision: Union[str, None] = '4a3b9f1d2c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itinerary_items', sa.Column('visited_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itinerary_items', 'visited_at')
    # ### end Alembic commands ###
