"""add_business_status_to_pois

Revision ID: 4a63dad117b1
Revises: c499c6dd9103
Create Date: 2026-03-26 20:53:14.019365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a63dad117b1'
down_revision: Union[str, None] = 'c499c6dd9103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pois', sa.Column('business_status', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pois', 'business_status')
    # ### end Alembic commands ###
