"""add_is_indoor_visitable_to_pois

Revision ID: 8475178a6524
Revises: 9bad6ff473b0
Create Date: 2026-03-25 11:53:58.686285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8475178a6524'
down_revision: Union[str, None] = '9bad6ff473b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pois', sa.Column('is_indoor_visitable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pois', 'is_indoor_visitable')
    # ### end Alembic commands ###
