"""add_poi_classification_logs

Revision ID: cff274140002
Revises: 4a63dad117b1
Create Date: 2026-03-27 19:24:04.821315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cff274140002'
down_revision: Union[str, None] = '4a63dad117b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi_classification_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('poi_id', sa.Uuid(), nullable=False),
    sa.Column('poi_name', sa.String(length=255), nullable=False),
    sa.Column('llm1_category', sa.String(length=50), nullable=True),
    sa.Column('llm1_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm1_is_indoor', sa.Boolean(), nullable=True),
    sa.Column('llm1_reasoning', sa.Text(), nullable=True),
    sa.Column('llm2_category', sa.String(length=50), nullable=True),
    sa.Column('llm2_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm2_is_indoor', sa.Boolean(), nullable=True),
    sa.Column('llm2_reasoning', sa.Text(), nullable=True),
    sa.Column('llm3_final_category', sa.String(length=50), nullable=True),
    sa.Column('llm3_final_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm3_final_is_indoor', sa.Boolean(), nullable=True),
    sa.Column('llm3_confidence', sa.String(length=10), nullable=True),
    sa.Column('llm3_reasoning', sa.Text(), nullable=True),
    sa.Column('category_agreement', sa.Boolean(), nullable=True),
    sa.Column('vector_cosine_distance', sa.Float(), nullable=True),
    sa.Column('final_category', sa.String(length=50), nullable=True),
    sa.Column('final_confidence', sa.String(length=10), nullable=True),
    sa.Column('city_name', sa.String(length=100), nullable=True),
    sa.Column('pipeline_run_id', sa.String(length=100), nullable=True),
    sa.Column('classified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poi_classification_logs')
    # ### end Alembic commands ###
