"""soft delete user_experience_choices

Revision ID: d2b427d115cc
Revises: 3e28afe586af
Create Date: 2026-03-23 21:15:54.941589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b427d115cc'
down_revision: Union[str, None] = '3e28afe586af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_experience_choices', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('user_experience_choices', 'experience_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('user_experience_choices_experience_id_fkey'), 'user_experience_choices', type_='foreignkey')
    op.create_foreign_key(None, 'user_experience_choices', 'city_experiences', ['experience_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_experience_choices', type_='foreignkey')
    op.create_foreign_key(op.f('user_experience_choices_experience_id_fkey'), 'user_experience_choices', 'city_experiences', ['experience_id'], ['id'])
    op.alter_column('user_experience_choices', 'experience_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('user_experience_choices', 'is_deleted')
    # ### end Alembic commands ###
